[package]
name = "rsmpi-session"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]
edition = "2018"
license = "MIT"

[dependencies.mpi]
git = "https://github.com/bsteinb/rsmpi"
default-features = false